#Clase 1
spring.application.name=tienda
# Render asigna PORT; en tu Mac usa 8081
server.port=${PORT:8081}


#Clase 2
#Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en producción "true"
spring.thymeleaf.cache=false


#Clase 3
# En Render se toman de las variables de entorno; en tu Mac usa los valores locales
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/techshop}

#Usuario y clave de creaTablas.sql
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:TuNuevaClave123!}


#Driver y plataforma de comunicacion
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mostrar informacion en log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE


#Clase 4
#Esta informacion se utiliza para obtener acceso a su storage.
firebase.bucket.name=techshop-d82c8.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-d82c8-firebase-adminsdk-fbsvc-cff63e5f3c.json